#!/usr/env/bin python3
"""LLM diagnostic layer for nowcast MVP.

Reads the forecast.json generated by nowcast.py, extracts key signals,
and queries the deepseek-v4-pro model to generate a structured diagnostic report.
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

from openai import OpenAI

PROMPT_TEMPLATE = """\
你是一位专业的气象播报员。你的任务是根据雷达外推数据和官方短临预报，为“科技四路文体公园”的网球爱好者提供一份专业、清晰、易懂的短临天气预报。
语气要像新闻里的天气预报一样专业、客观，同时要明确告知用户未来两小时内的降雨情况和场地影响。

请注意：**你绝不能凭空捏造数据**，必须严格基于提供的特征数据进行播报。如果雷达数据与官方数据存在不一致，请在播报中以专业的口吻进行客观解读（例如：“虽然雷达显示周边有微弱水汽，但预计不会形成有效降雨”）。

以下是当前气象算法输出的核心特征：
```json
{context}
```

请输出一份纯净合法的 JSON 格式，不要包含任何 Markdown 代码块包裹（如```json），结构严格如下：
{{
  "weather_report": {{
    "headline": "一句话核心播报（例如：未来两小时天气平稳，适宜户外运动）",
    "professional_summary": "新闻播报风格的详细预报，综合雷达回波、降雨概率和官方预测，客观描述未来120分钟的天气趋势。",
    "court_condition_forecast": "对网球场地状况的具体预测（例如：预计场地保持干爽 / 可能会有短时阵雨导致湿滑）",
    "data_consistency_note": "一句话说明雷达与官方数据的一致性（客观解释，不涉及系统Bug等技术词汇）"
  }}
}}
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="LLM diagnostic script for weather forecast.")
    parser.add_argument(
        "--forecast",
        default="output/forecast.json",
        help="Input JSON generated by nowcast.py",
    )
    parser.add_argument(
        "--output",
        default="output/diagnosis.json",
        help="Output JSON for LLM diagnosis",
    )
    parser.add_argument(
        "--api-key",
        default=os.getenv("DASHSCOPE_API_KEY", "REDACTED_API_KEY"),
        help="Aliyun DashScope API Key",
    )
    return parser.parse_args()


def extract_context(forecast: dict[str, Any]) -> dict[str, Any]:
    """Extract streamlined context to save tokens and focus the LLM."""
    return {
        "rain_probability": forecast.get("rain_probability"),
        "confidence": forecast.get("confidence"),
        "current": forecast.get("current"),
        "playable_coverage_ratio": forecast.get("playable_coverage_ratio"),
        "motion_consistency": forecast.get("motion", {}).get("consistency"),
        "official_qpf6min_summary": forecast.get("official_qpf6min_summary"),
        "diagnostics": forecast.get("diagnostics"),
    }


def main() -> int:
    args = parse_args()
    
    forecast_path = Path(args.forecast)
    if not forecast_path.exists():
        print(f"Error: {forecast_path} does not exist. Run nowcast.py first.", file=sys.stderr)
        return 1

    try:
        forecast_data = json.loads(forecast_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"Error parsing {forecast_path}: {e}", file=sys.stderr)
        return 1

    context = extract_context(forecast_data)
    prompt = PROMPT_TEMPLATE.format(context=json.dumps(context, ensure_ascii=False, indent=2))

    client = OpenAI(
        api_key=args.api_key,
        base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
    )

    print("Sending context to deepseek-v4-pro for diagnosis...")
    messages = [{"role": "user", "content": prompt}]
    
    try:
        completion = client.chat.completions.create(
            model="deepseek-v4-pro",
            messages=messages,
            # Enable thinking mode (specific to DashScope implementation)
            extra_body={"enable_thinking": True},
            stream=True,
            stream_options={"include_usage": True},
        )
    except Exception as e:
        print(f"Failed to call Aliyun API: {e}", file=sys.stderr)
        return 1

    reasoning_content = ""
    answer_content = ""
    is_answering = False

    print("\n" + "=" * 20 + " 思考过程 " + "=" * 20 + "\n")

    for chunk in completion:
        if not chunk.choices:
            if hasattr(chunk, "usage") and chunk.usage:
                print("\n" + "=" * 20 + " Token 消耗 " + "=" * 20 + "\n")
                print(chunk.usage)
            continue

        delta = chunk.choices[0].delta

        # Collect and print reasoning content
        if hasattr(delta, "reasoning_content") and delta.reasoning_content is not None:
            if not is_answering:
                sys.stdout.write(delta.reasoning_content)
                sys.stdout.flush()
                reasoning_content += delta.reasoning_content

        # Collect and print answer content
        if hasattr(delta, "content") and delta.content is not None:
            if not is_answering:
                print("\n\n" + "=" * 20 + " 诊断结果 " + "=" * 20 + "\n")
                is_answering = True
            sys.stdout.write(delta.content)
            sys.stdout.flush()
            answer_content += delta.content

    print("\n\n" + "=" * 50)

    # Clean up JSON if LLM output markdown wrapper accidentally
    answer_content = answer_content.strip()
    if answer_content.startswith("```json"):
        answer_content = answer_content[7:]
    if answer_content.startswith("```"):
        answer_content = answer_content[3:]
    if answer_content.endswith("```"):
        answer_content = answer_content[:-3]
    answer_content = answer_content.strip()

    try:
        parsed_diagnosis = json.loads(answer_content)
    except json.JSONDecodeError as e:
        print(f"Warning: Failed to parse LLM output as JSON: {e}", file=sys.stderr)
        # Attempt to wrap it as raw text if parsing fails
        parsed_diagnosis = {"weather_report": {"headline": "JSON Parse Error", "raw_output": answer_content}}

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(parsed_diagnosis, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    
    print(f"\nSaved diagnosis to {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
