#!/usr/env/bin python3
"""LLM diagnostic layer for nowcast MVP.

Reads the forecast.json generated by nowcast.py, extracts key signals,
and queries the deepseek-v4-pro model to generate a structured weather report
with three parts: data presentation, reasoning process, and conclusion.
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

from openai import OpenAI

PROMPT_TEMPLATE = """\
你是一位专业的气象分析师，同时也是"科技四路文体公园"网球场的天气顾问。

你的任务是基于以下多源气象数据，为网球爱好者生成一份 **三段式短临天气分析报告**。

## 你必须严格遵守的规则
1. **绝不能凭空捏造数据**，所有分析必须引用输入数据中的具体数值。
2. 推理过程中必须逐条引用证据，说明每条证据支持什么结论。
3. 如果多个数据源之间存在矛盾，必须明确指出并解释可能原因。

## 你需要掌握的气象判断经验（华南沿海适用）
- 雨量计 `rain_5min_mm > 0` 是地面正在下雨的铁证。
- 湿度 < 70%：弱回波很难落地成雨。湿度 75%-85%：弱回波有机会零星小雨。湿度 > 85%：只要有回波经过，落地成雨概率明显增加。
- 能见度明显下降（降到几公里以内）+ 高湿度 + 有回波 = 低层水汽充足，降雨概率上升。
- 风向突变 + 风速增大 + 湿度上升 = 警惕阵风锋或海陆风辐合触发局地对流。
- 当天常规预报有"阵雨/雷阵雨"背景时，即使短时无雨，也不能完全排除局地新生。
- 回波面积扩大、颜色变深 = 发展中；颜色变浅、边缘破碎 = 衰减中。

## 输入数据
```json
{context}
```

## 输出要求
请输出纯净合法的 JSON 格式，不要包含任何 Markdown 代码块包裹（如```json），结构严格如下：
{{
  "data_summary": {{
    "radar": "用一两句话描述雷达回波的当前状况（有无回波、强度、覆盖范围、移动趋势）",
    "station": "用一两句话描述地面气象站实况（温度、湿度、风力风向、雨量计读数、能见度）",
    "official_forecast": "用一句话概括官方短临预报的结论"
  }},
  "reasoning": [
    {{
      "evidence": "引用的具体数据点（如：humidity_pct=79, rain_5min_mm=0）",
      "inference": "基于这条证据得出的判断（如：湿度处于中等偏高水平，弱回波有一定落地可能，但雨量计确认目前无雨）"
    }},
    {{
      "evidence": "另一条数据点...",
      "inference": "对应的推断..."
    }}
  ],
  "conclusion": {{
    "headline": "一句话核心结论（如：未来两小时天气平稳，适宜户外运动）",
    "approach_risk": "接近风险：雷达上游回波是否会扫到球场，用'低/中/高'加一句解释",
    "landing_probability": "落地概率：结合湿度、雨量计、能见度判断回波能否形成有效降雨",
    "spawning_risk": "新生风险：高湿、风向变化、午后、常规预报阵雨背景是否支持局地新生对流",
    "court_impact": "对网球场地的具体影响预测（场地干爽/可能湿滑/不宜打球）",
    "suggestion": "结合天气和环境的打球建议（如体感温度高注意补水、东风3级注意发球抛球偏移等）"
  }}
}}
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="LLM diagnostic script for weather forecast.")
    parser.add_argument(
        "--forecast",
        default="output/forecast.json",
        help="Input JSON generated by nowcast.py",
    )
    parser.add_argument(
        "--output",
        default="output/diagnosis.json",
        help="Output JSON for LLM diagnosis",
    )
    parser.add_argument(
        "--api-key",
        default=os.getenv("DASHSCOPE_API_KEY", "REDACTED_API_KEY"),
        help="Aliyun DashScope API Key",
    )
    return parser.parse_args()


def extract_context(forecast: dict[str, Any]) -> dict[str, Any]:
    """Extract streamlined context to save tokens and focus the LLM."""
    return {
        "rain_probability": forecast.get("rain_probability"),
        "confidence": forecast.get("confidence"),
        "current_radar": forecast.get("current"),
        "playable_coverage_ratio": forecast.get("playable_coverage_ratio"),
        "motion": forecast.get("motion"),
        "station_realtime": forecast.get("station_realtime"),
        "official_qpf6min_summary": forecast.get("official_qpf6min_summary"),
        "diagnostics": forecast.get("diagnostics"),
    }


def main() -> int:
    args = parse_args()
    
    forecast_path = Path(args.forecast)
    if not forecast_path.exists():
        print(f"Error: {forecast_path} does not exist. Run nowcast.py first.", file=sys.stderr)
        return 1

    try:
        forecast_data = json.loads(forecast_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"Error parsing {forecast_path}: {e}", file=sys.stderr)
        return 1

    context = extract_context(forecast_data)
    prompt = PROMPT_TEMPLATE.format(context=json.dumps(context, ensure_ascii=False, indent=2))

    client = OpenAI(
        api_key=args.api_key,
        base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
    )

    print("Sending context to deepseek-v4-pro for analysis...")
    messages = [{"role": "user", "content": prompt}]
    
    try:
        completion = client.chat.completions.create(
            model="deepseek-v4-pro",
            messages=messages,
            # Enable thinking mode (specific to DashScope implementation)
            extra_body={"enable_thinking": True},
            stream=True,
            stream_options={"include_usage": True},
        )
    except Exception as e:
        print(f"Failed to call Aliyun API: {e}", file=sys.stderr)
        return 1

    reasoning_content = ""
    answer_content = ""
    is_answering = False

    print("\n" + "=" * 20 + " 模型思考过程 " + "=" * 20 + "\n")

    for chunk in completion:
        if not chunk.choices:
            if hasattr(chunk, "usage") and chunk.usage:
                print("\n" + "=" * 20 + " Token 消耗 " + "=" * 20 + "\n")
                print(chunk.usage)
            continue

        delta = chunk.choices[0].delta

        # Collect and print reasoning content
        if hasattr(delta, "reasoning_content") and delta.reasoning_content is not None:
            if not is_answering:
                sys.stdout.write(delta.reasoning_content)
                sys.stdout.flush()
                reasoning_content += delta.reasoning_content

        # Collect and print answer content
        if hasattr(delta, "content") and delta.content is not None:
            if not is_answering:
                print("\n\n" + "=" * 20 + " 分析报告 " + "=" * 20 + "\n")
                is_answering = True
            sys.stdout.write(delta.content)
            sys.stdout.flush()
            answer_content += delta.content

    print("\n\n" + "=" * 50)

    # Clean up JSON if LLM output markdown wrapper accidentally
    answer_content = answer_content.strip()
    if answer_content.startswith("```json"):
        answer_content = answer_content[7:]
    if answer_content.startswith("```"):
        answer_content = answer_content[3:]
    if answer_content.endswith("```"):
        answer_content = answer_content[:-3]
    answer_content = answer_content.strip()

    try:
        parsed_result = json.loads(answer_content)
    except json.JSONDecodeError as e:
        print(f"Warning: Failed to parse LLM output as JSON: {e}", file=sys.stderr)
        parsed_result = {"error": "JSON Parse Error", "raw_output": answer_content}

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(parsed_result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    
    print(f"\nSaved report to {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
