#!/usr/env/bin python3
"""LLM diagnostic layer for nowcast MVP.

Reads the forecast.json generated by nowcast.py, extracts key signals,
and queries the deepseek-v4-pro model to generate a structured diagnostic report.
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

from openai import OpenAI

PROMPT_TEMPLATE = """\
你是一个高级气象开发与调试工程师。你的任务是分析雷达推演和官方短临预报(QPF)之间的潜在冲突，提供调试建议。
请注意：**你绝不能直接修改或提供新的降雨概率**，你的角色只是解释现状、分析冲突可能的原因。

以下是当前气象算法输出的核心特征：
```json
{context}
```

请根据这些特征，分析当前的雷达数据与官方预测是否冲突，以及可能的系统原因。
输出必须是纯净合法的 JSON 格式，不要包含任何 Markdown 代码块包裹（如```json），结构严格如下：
{{
  "llm_diagnosis": {{
    "summary": "一句话总结当前的冲突或诊断结果",
    "likely_causes": ["可能原因1", "可能原因2"],
    "recommended_debug_steps": ["调试建议1", "调试建议2"],
    "should_adjust_probability": false
  }}
}}
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="LLM diagnostic script for weather forecast.")
    parser.add_argument(
        "--forecast",
        default="output/forecast.json",
        help="Input JSON generated by nowcast.py",
    )
    parser.add_argument(
        "--output",
        default="output/diagnosis.json",
        help="Output JSON for LLM diagnosis",
    )
    parser.add_argument(
        "--api-key",
        default=os.getenv("DASHSCOPE_API_KEY", "REDACTED_API_KEY"),
        help="Aliyun DashScope API Key",
    )
    return parser.parse_args()


def extract_context(forecast: dict[str, Any]) -> dict[str, Any]:
    """Extract streamlined context to save tokens and focus the LLM."""
    return {
        "rain_probability": forecast.get("rain_probability"),
        "confidence": forecast.get("confidence"),
        "current": forecast.get("current"),
        "playable_coverage_ratio": forecast.get("playable_coverage_ratio"),
        "motion_consistency": forecast.get("motion", {}).get("consistency"),
        "official_qpf6min_summary": forecast.get("official_qpf6min_summary"),
        "diagnostics": forecast.get("diagnostics"),
    }


def main() -> int:
    args = parse_args()
    
    forecast_path = Path(args.forecast)
    if not forecast_path.exists():
        print(f"Error: {forecast_path} does not exist. Run nowcast.py first.", file=sys.stderr)
        return 1

    try:
        forecast_data = json.loads(forecast_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"Error parsing {forecast_path}: {e}", file=sys.stderr)
        return 1

    context = extract_context(forecast_data)
    prompt = PROMPT_TEMPLATE.format(context=json.dumps(context, ensure_ascii=False, indent=2))

    client = OpenAI(
        api_key=args.api_key,
        base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
    )

    print("Sending context to deepseek-v4-pro for diagnosis...")
    messages = [{"role": "user", "content": prompt}]
    
    try:
        completion = client.chat.completions.create(
            model="deepseek-v4-pro",
            messages=messages,
            # Enable thinking mode (specific to DashScope implementation)
            extra_body={"enable_thinking": True},
            stream=True,
            stream_options={"include_usage": True},
        )
    except Exception as e:
        print(f"Failed to call Aliyun API: {e}", file=sys.stderr)
        return 1

    reasoning_content = ""
    answer_content = ""
    is_answering = False

    print("\n" + "=" * 20 + " 思考过程 " + "=" * 20 + "\n")

    for chunk in completion:
        if not chunk.choices:
            if hasattr(chunk, "usage") and chunk.usage:
                print("\n" + "=" * 20 + " Token 消耗 " + "=" * 20 + "\n")
                print(chunk.usage)
            continue

        delta = chunk.choices[0].delta

        # Collect and print reasoning content
        if hasattr(delta, "reasoning_content") and delta.reasoning_content is not None:
            if not is_answering:
                sys.stdout.write(delta.reasoning_content)
                sys.stdout.flush()
                reasoning_content += delta.reasoning_content

        # Collect and print answer content
        if hasattr(delta, "content") and delta.content is not None:
            if not is_answering:
                print("\n\n" + "=" * 20 + " 诊断结果 " + "=" * 20 + "\n")
                is_answering = True
            sys.stdout.write(delta.content)
            sys.stdout.flush()
            answer_content += delta.content

    print("\n\n" + "=" * 50)

    # Clean up JSON if LLM output markdown wrapper accidentally
    answer_content = answer_content.strip()
    if answer_content.startswith("```json"):
        answer_content = answer_content[7:]
    if answer_content.startswith("```"):
        answer_content = answer_content[3:]
    if answer_content.endswith("```"):
        answer_content = answer_content[:-3]
    answer_content = answer_content.strip()

    try:
        parsed_diagnosis = json.loads(answer_content)
    except json.JSONDecodeError as e:
        print(f"Warning: Failed to parse LLM output as JSON: {e}", file=sys.stderr)
        # Attempt to wrap it as raw text if parsing fails
        parsed_diagnosis = {"llm_diagnosis": {"summary": "JSON Parse Error", "raw_output": answer_content}}

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(parsed_diagnosis, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    
    print(f"\nSaved diagnosis to {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
